export interface Doctor {
  id: number;
  name: string;
  specialty: string;
  rating: number;
  reviews: number;
  experience: string;
  price: number;
  image: string;
  available: boolean;
  description: string;
  education: string;
  languages: string[];
  nextAvailable?: string;
}

export const doctors: Doctor[] = [
  {
    id: 1,
    name: "Dr. Sarah Anderson",
    specialty: "Psikolog Klinis",
    rating: 4.9,
    reviews: 156,
    experience: "12 tahun",
    price: 150000,
    image: "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&dpr=2&q=80",
    available: true,
    description: "Spesialis dalam menangani kecemasan dan depresi dengan pendekatan CBT",
    education: "S2 Psikologi Klinis, Universitas Indonesia",
    languages: ["Indonesia", "English"],
    nextAvailable: "Hari ini, 14:00",
  },
  {
    id: 2,
    name: "Dr. Michael Chen",
    specialty: "Psikolog Anak",
    rating: 4.8,
    reviews: 142,
    experience: "10 tahun",
    price: 175000,
    image: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&dpr=2&q=80",
    available: true,
    description: "Ahli dalam psikologi anak dan perkembangan dengan pengalaman lebih dari 10 tahun",
    education: "S2 Psikologi Anak, National University of Singapore",
    languages: ["Indonesia", "English", "Mandarin"],
    nextAvailable: "Besok, 09:00",
  },
  {
    id: 3,
    name: "Dr. Amanda Foster",
    specialty: "Terapi Keluarga",
    rating: 4.9,
    reviews: 203,
    experience: "15 tahun",
    price: 200000,
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&dpr=2&q=80",
    available: false,
    description: "Terapis keluarga bersertifikat dengan fokus pada resolusi konflik",
    education: "S3 Terapi Keluarga, Harvard University",
    languages: ["Indonesia", "English"],
  },
  {
    id: 4,
    name: "Dr. David Wilson",
    specialty: "Psikolog Dewasa",
    rating: 4.7,
    reviews: 128,
    experience: "8 tahun",
    price: 140000,
    image: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&dpr=2&q=80",
    available: true,
    description: "Membantu individu dewasa mengatasi stress dan masalah kehidupan",
    education: "S2 Psikologi, Universitas Gadjah Mada",
    languages: ["Indonesia"],
    nextAvailable: "Hari ini, 16:30",
  },
  {
    id: 5,
    name: "Dr. Lisa Martinez",
    specialty: "Terapi Trauma",
    rating: 4.9,
    reviews: 187,
    experience: "14 tahun",
    price: 190000,
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&dpr=2&q=80",
    available: true,
    description: "Spesialis trauma dengan pendekatan EMDR dan mindfulness",
    education: "S2 Psikologi Trauma, Stanford University",
    languages: ["Indonesia", "English", "Spanish"],
    nextAvailable: "Besok, 10:00",
  },
  {
    id: 6,
    name: "Dr. Robert Taylor",
    specialty: "Psikolog Remaja",
    rating: 4.8,
    reviews: 165,
    experience: "11 tahun",
    price: 160000,
    image: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&dpr=2&q=80",
    available: true,
    description: "Ahli dalam menangani masalah remaja dan transisi kehidupan",
    education: "S2 Psikologi Remaja, Universitas Airlangga",
    languages: ["Indonesia", "English"],
    nextAvailable: "Hari ini, 15:00",
  },
  {
    id: 7,
    name: "Dr. Emily Zhang",
    specialty: "Psikolog Klinis",
    rating: 4.7,
    reviews: 134,
    experience: "9 tahun",
    price: 145000,
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&dpr=2&q=80",
    available: true,
    description: "Fokus pada gangguan mood dan kecemasan dengan terapi holistik",
    education: "S2 Psikologi Klinis, Universitas Padjadjaran",
    languages: ["Indonesia", "Mandarin"],
    nextAvailable: "Besok, 13:00",
  },
  {
    id: 8,
    name: "Dr. James Kumar",
    specialty: "Psikolog Dewasa",
    rating: 4.6,
    reviews: 98,
    experience: "7 tahun",
    price: 135000,
    image: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&dpr=2&q=80",
    available: false,
    description: "Membantu profesional mengatasi burnout dan stress kerja",
    education: "S2 Psikologi Industri, RMIT University",
    languages: ["Indonesia", "English", "Hindi"],
  },
  {
    id: 9,
    name: "Dr. Sophie Laurent",
    specialty: "Terapi Keluarga",
    rating: 4.8,
    reviews: 176,
    experience: "13 tahun",
    price: 195000,
    image: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&dpr=2&q=80",
    available: true,
    description: "Spesialis konseling pernikahan dan terapi pasangan",
    education: "S2 Terapi Keluarga, Sorbonne University",
    languages: ["Indonesia", "English", "French"],
    nextAvailable: "Besok, 11:00",
  },
  {
    id: 10,
    name: "Dr. Ahmed Hassan",
    specialty: "Psikolog Anak",
    rating: 4.7,
    reviews: 145,
    experience: "10 tahun",
    price: 170000,
    image: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&dpr=2&q=80",
    available: true,
    description: "Ahli dalam terapi bermain dan masalah perilaku anak",
    education: "S2 Psikologi Anak, American University of Cairo",
    languages: ["Indonesia", "English", "Arabic"],
    nextAvailable: "Hari ini, 17:00",
  },
  {
    id: 11,
    name: "Dr. Maria Santos",
    specialty: "Terapi Trauma",
    rating: 4.9,
    reviews: 192,
    experience: "16 tahun",
    price: 210000,
    image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=400&dpr=2&q=80",
    available: true,
    description: "Spesialis PTSD dan trauma kompleks dengan pendekatan trauma-informed",
    education: "S3 Psikologi Trauma, University of Melbourne",
    languages: ["Indonesia", "English"],
    nextAvailable: "Besok, 09:30",
  },
  {
    id: 12,
    name: "Dr. Kevin Park",
    specialty: "Psikolog Remaja",
    rating: 4.6,
    reviews: 112,
    experience: "8 tahun",
    price: 155000,
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&dpr=2&q=80",
    available: false,
    description: "Membantu remaja menghadapi tekanan akademik dan sosial",
    education: "S2 Psikologi Remaja, Yonsei University",
    languages: ["Indonesia", "English", "Korean"],
  },
  {
    id: 13,
    name: "Dr. Rachel Green",
    specialty: "Psikolog Klinis",
    rating: 4.8,
    reviews: 168,
    experience: "12 tahun",
    price: 165000,
    image: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&dpr=2&q=80",
    available: true,
    description: "Spesialis gangguan kecemasan dan panic disorder",
    education: "S2 Psikologi Klinis, University of Sydney",
    languages: ["Indonesia", "English"],
    nextAvailable: "Hari ini, 18:00",
  },
  {
    id: 14,
    name: "Dr. Thomas Anderson",
    specialty: "Psikolog Dewasa",
    rating: 4.7,
    reviews: 139,
    experience: "11 tahun",
    price: 150000,
    image: "https://images.unsplash.com/photo-1519345182560-3f2917c472ef?w=400&dpr=2&q=80",
    available: true,
    description: "Fokus pada pengembangan diri dan manajemen emosi",
    education: "S2 Psikologi, Monash University",
    languages: ["Indonesia", "English"],
    nextAvailable: "Besok, 14:00",
  },
  {
    id: 15,
    name: "Dr. Nina Patel",
    specialty: "Terapi Keluarga",
    rating: 4.9,
    reviews: 201,
    experience: "15 tahun",
    price: 205000,
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&dpr=2&q=80",
    available: true,
    description: "Terapis keluarga dengan spesialisasi parenting dan komunikasi",
    education: "S2 Terapi Keluarga, University of Mumbai",
    languages: ["Indonesia", "English", "Hindi"],
    nextAvailable: "Besok, 10:30",
  },
  {
    id: 16,
    name: "Dr. Lucas Silva",
    specialty: "Psikolog Anak",
    rating: 4.6,
    reviews: 127,
    experience: "9 tahun",
    price: 165000,
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&dpr=2&q=80",
    available: false,
    description: "Ahli dalam autism spectrum dan developmental disorders",
    education: "S2 Psikologi Perkembangan, University of São Paulo",
    languages: ["Indonesia", "English", "Portuguese"],
  },
  {
    id: 17,
    name: "Dr. Olivia Brown",
    specialty: "Terapi Trauma",
    rating: 4.8,
    reviews: 183,
    experience: "13 tahun",
    price: 185000,
    image: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&dpr=2&q=80",
    available: true,
    description: "Spesialis trauma masa kecil dengan pendekatan attachment-based",
    education: "S2 Psikologi Trauma, King's College London",
    languages: ["Indonesia", "English"],
    nextAvailable: "Hari ini, 16:00",
  },
  {
    id: 18,
    name: "Dr. Daniel Kim",
    specialty: "Psikolog Remaja",
    rating: 4.7,
    reviews: 154,
    experience: "10 tahun",
    price: 160000,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&dpr=2&q=80",
    available: true,
    description: "Membantu remaja dengan self-esteem dan identitas",
    education: "S2 Psikologi Remaja, Seoul National University",
    languages: ["Indonesia", "English", "Korean"],
    nextAvailable: "Besok, 15:00",
  },
];
